#
# Module manifest for module 'module'
#
# Generated by: pwujczyk
#
# Generated on: 6/17/2022 7:21:40 PM
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ProductivityTools.GetServiceDescription.psm1'

# Version number of this module.
ModuleVersion = '0.0.5'

# ID used to uniquely identify this module
GUID = 'c66c4692-ed60-4079-a452-7c97142b3db7'

# Author of this module
Author = 'Pawel Wujczyk'

# Company or vendor of this module
CompanyName = 'ProductivityTools.tech'

# Description of the functionality provided by this module
Description = 'Gets service description for service name'

# Functions to export from this module
FunctionsToExport = 'Get-ServiceDescription'


PrivateData = @{
    
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('OneDrive')
    
        # A URL to the main website for this project.
        ProjectUri = 'https://www.powershellgallery.com/packages/ProductivityTools.GetServiceDescription'
    
                # A URL to an icon representing this module.
        IconUri = 'http://cdn.productivitytools.tech/images/PT/ProductivityTools_blue_85px_3.png'
            } # End of PSData hashtable
    } # End of PrivateData hashtable   

# HelpInfo URI of this module
HelpInfoURI = 'https://www.powershellgallery.com/packages/ProductivityTools.GetServiceDescription'

}

